version: '3'
networks:
  default:
    external:
      name: webproxy_webproxy-net

services:
  app:
    image: shrikantpatnaik/s3gallery
    container_name: photos-site
    ports:
      - "${PHOTO_SITE_PORT}:3000"
    links:
      - mongo
    volumes:
      - ${METEOR_SETTINGS_FOLDER}:/root/app/settings
    restart: always
    environment:
      ROOT_URL: ${METEOR_ROOT_URL}
      MONGO_URL: mongodb://mongo:27017/meteor
      VIRTUAL_HOST: ${PHOTO_SITE_URL}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: ${PHOTO_SITE_PORT}

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - "${MONGO_FILES_PATH}:/data/db"
    command: mongod --storageEngine=wiredTiger
