version: '3'
networks:
  default:
    external:
      name: webproxy_webproxy-net

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:9090"
    volumes:
      - ${PROMETHEUS_CONFIG_FILES_PATH}:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-web.console.libraries=/etc/prometheus/console_libraries'
      - '-web.console.templates=/etc/prometheus/consoles'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.target-heap-size=1073741824'
      - '-storage.local.retention=200h'
      - '-web.external-url=${PROMETHEUS_URL}'
    environment:
      VIRTUAL_HOST: ${PROMETHEUS_URL}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: ${PROMETHEUS_PORT}
      LETSENCRYPT_HOST: ${PROMETHEUS_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL_ID}

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - "127.0.0.1:${ALERTMANAGER_PORT}:9093"
    volumes:
      - ${ALERTMANAGER_CONFIG_FILES_PATH}:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
      - '-web.external-url=${ALERTMANAGER_URL}'
    environment:
      VIRTUAL_HOST: ${ALERTMANAGER_URL}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: ${ALERTMANAGER_PORT}
      LETSENCRYPT_HOST: ${ALERTMANAGER_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL_ID}

  sms:
    image: swatto/promtotwilio:latest
    environment:
      SID: ${TWILIO_SID}
      TOKEN: ${TWILIO_TOKEN}
      RECEIVER: ${SMS_RECEIVER}
      SENDER: ${SMS_SENDER}

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    restart: always
    volumes:
      - ${BLACKBOX_EXPORTER_CONFIG_FILES_PATH}:/config
    command:
      - '-config.file=/config/blackbox.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      VIRTUAL_HOST: ${GRAFANA_URL}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: ${GRAFANA_PORT}
      LETSENCRYPT_HOST: ${GRAFANA_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL_ID}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
