version: '3'
networks:
  default:
    external:
      name: webproxy_webproxy-net

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "127.0.0.1:${WORDPRESS_PORT}:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
       VIRTUAL_HOST: ${WORDPRESS_URL}
       VIRTUAL_PROTO: http
       VIRTUAL_PORT: ${WORDPRESS_PORT}
       LETSENCRYPT_HOST: ${WORDPRESS_URL}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL_ID}
volumes:
    db_data:
