version: '3'

services:
  iperf3-server:
    image: networkstatic/iperf3
    container_name: iperf3-server
    restart: always
    network_mode: "host"
    ports:
      - "5201:5201"
    command:
      - '-s'
      - '-V'
