version: '3'
networks:
  default:
    external:
      name: webproxy_webproxy-net

services:
  ghost:
    image: ghost
    container_name: ghost-main
    ports:
     - "127.0.0.1:${GHOST_PORT}:2368"
    restart: always
    volumes:
     - ${GHOST_FILES_PATH}:/var/lib/ghost/content
    environment:
      url: https://${GHOST_URL}/
      VIRTUAL_HOST: ${GHOST_URL}
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: ${GHOST_PORT}
      LETSENCRYPT_HOST: ${GHOST_URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL_ID}
